import { ensureNflPlaystageV886AStyles } from './gamecast-v886a-styles.js?v=88.6a';
const TEAM_COLORS={ARI:['#97233F','#000'],ATL:['#A71930','#000'],BAL:['#241773','#000'],BUF:['#00338D','#C60C30'],CAR:['#0085CA','#101820'],CHI:['#0B162A','#C83803'],CIN:['#FB4F14','#000'],CLE:['#311D00','#FF3C00'],DAL:['#003594','#041E42'],DEN:['#FB4F14','#002244'],DET:['#0076B6','#B0B7BC'],GB:['#203731','#FFB612'],HOU:['#03202F','#A71930'],IND:['#002C5F','#A2AAAD'],JAX:['#006778','#101820'],KC:['#E31837','#FFB81C'],LV:['#000','#A5ACAF'],LAC:['#0080C6','#FFC20E'],LA:['#003594','#FFA300'],MIA:['#008E97','#FC4C02'],MIN:['#4F2683','#FFC62F'],NE:['#002244','#C60C30'],NO:['#D3BC8D','#101820'],NYG:['#0B2265','#A71930'],NYJ:['#125740','#fff'],PHI:['#004C54','#A5ACAF'],PIT:['#101820','#FFB612'],SF:['#AA0000','#B3995D'],SEA:['#002244','#69BE28'],TB:['#D50A0A','#34302B'],TEN:['#0C2340','#4B92DB'],WAS:['#5A1414','#FFB612']};
const esc=v=>String(v??'');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number.isFinite(+v)?+v:a));
const tObj=(g,s)=>(g&&g[s])||{};
const tAb=(g,s)=>esc(tObj(g,s).abbr||tObj(g,s).code||(s==='away'?'AWY':'HOME')).toUpperCase();
const tName=(g,s)=>esc(tObj(g,s).name||tObj(g,s).nickname||tAb(g,s));
const tLogo=(g,s)=>esc(tObj(g,s).logo||tObj(g,s).logoUrl||'');
const tRec=(g,s)=>esc(tObj(g,s).record||'0-0');
const colors=(g,s)=>TEAM_COLORS[tAb(g,s)] || ['#0d3b73','#2c6e2f'];
const init=n=>esc(n).trim().slice(0,1).toUpperCase()||'P';
function possessionSide(g){const p=String(g?.possession||g?.liveScore?.possession||g?.hasBall||'').toUpperCase(); const a=tAb(g,'away'), h=tAb(g,'home'); if(p.includes(a)||p==='AWAY') return 'away'; if(p.includes(h)||p==='HOME') return 'home'; const s=String(g?.liveNote||g?.statusText||'').toUpperCase(); if(s.includes(`${a} HAS THE BALL`)||s.includes(`${a} BALL`)) return 'away'; if(s.includes(`${h} HAS THE BALL`)||s.includes(`${h} BALL`)) return 'home'; return 'away';}
function ballState(g){const raw=String(g?.liveScore?.ballOn||g?.fieldPosition||g?.ballOn||'').trim(); let side=possessionSide(g), yd=50; const a=tAb(g,'away'), h=tAb(g,'home'); const m=raw.match(/([A-Z]{2,3})\s*(\d{1,2})/i); if(m){const ab=m[1].toUpperCase(); yd=clamp(parseInt(m[2],10),0,50); if(ab===a) side='away'; else if(ab===h) side='home';} else {const n=raw.match(/(\d{1,2})/); if(n) yd=clamp(parseInt(n[1],10),0,50);} return {side,yd,pct:clamp(side==='away'?50-yd:50+yd,3,97)}}
const dd=g=>esc(g?.liveScore?.downDistance||g?.downDistance||'1st & 10');
const fp=g=>{const b=ballState(g); return `${tAb(g,b.side)} ${b.yd}`};
function play(g){const p=g?.currentPlay||g?.liveScore?.currentPlay||{}; const f=g?.featuredPlayer||{}; return {title:p.title||g?.liveScore?.playTitle||'Current Play', desc:p.description||g?.liveScore?.description||g?.playText||'Live updates animate every snap.', name:p.playerName||f.name||'Featured Player', pos:p.playerPos||f.position||'QB', no:p.playerNo||f.number||'10', head:p.headshot||f.headshot||'', target:p.targetName||p.receiverName||'Hunter Henry', type:String(p.type||p.kind||p.playType||p.description||'pass right').toLowerCase(), plays:p.drivePlays||g?.drive?.plays||4, yards:p.driveYards||g?.drive?.yards||22, time:p.driveTime||g?.drive?.time||'2:39', yds:p.resultYards??p.yards??0, stats:p.featuredStats||f.stats||{compAtt:'8/10',yards:'96',td:'0',rtg:'118.3'}, drive:Array.isArray(p.driveSummary)&&p.driveSummary.length?p.driveSummary:[{text:'6-yd rush',dd:'1st & 10',fp:'NE 14'},{text:'12-yd pass',dd:'1st & 10',fp:'NE 26'},{text:'4-yd rush',dd:'1st & 10',fp:'NE 30'},{text:'Current Play',dd:dd(g),fp:fp(g),current:true}], chart:Array.isArray(p.chart)&&p.chart.length?p.chart:[44,44,45,46,45,44,49,52,46,43,47,48,49,50,49,53,54,56,58,55,59,61,63,65,68]};}
const wp=g=>{const a=clamp(g?.winProbAway??g?.liveScore?.winProbAway??g?.awayWinPct??68,0,100); return {away:Math.round(a),home:Math.round(100-a)}};
const chartPath=vals=>vals.map((v,i)=>[i*(100/Math.max(1,vals.length-1)),80-clamp(v,0,100)*.62]).map((p,i)=>`${i?'L':'M'}${p[0].toFixed(2)} ${p[1].toFixed(2)}`).join(' ');
function yardNums(){let s=''; for(let i=10;i<100;i+=10){const n=i===50?50:(i<50?i:100-i); s+=`<div class="tso-ps886a__yardNum" style="left:${i}%">${n}</div><div class="tso-ps886a__yardNum bot" style="left:${i}%">${n}</div>`;} return s;}
function formation(g){const p=play(g), b=ballState(g).pct, poss=possessionSide(g), attack=poss==='away'?1:-1;
 const los=b, fd=clamp(b+(attack*8),4,96);
 const offense=[{x:b-8*attack,y:64,r:'qb',tag:'Maye'},{x:b-4*attack,y:58,r:'line'},{x:b-3.1*attack,y:54,r:'line'},{x:b-2.2*attack,y:50,r:'line'},{x:b-1.2*attack,y:46,r:'line'},{x:b-.1*attack,y:42,r:'line'},{x:b+2.5*attack,y:68,r:'wr'},{x:b+4*attack,y:59,r:'rb'},{x:b+10*attack,y:39,r:'wr'},{x:b+12*attack,y:30,r:'wr'},{x:b+13*attack,y:72,r:'wr'}];
 const defense=[{x:b-1.5*attack,y:44},{x:b-.6*attack,y:49},{x:b+.2*attack,y:55},{x:b+1.1*attack,y:60},{x:b+2.4*attack,y:65},{x:b+4.4*attack,y:41},{x:b+5.4*attack,y:53},{x:b+8.8*attack,y:34},{x:b+9.8*attack,y:48},{x:b+10.4*attack,y:63},{x:b+11.2*attack,y:77}];
 let route={x1:offense[0].x,y1:offense[0].y,x2:offense[8].x,y2:offense[8].y-2,c1x:b+4*attack,c1y:46}; let key=8;
 if(p.type.includes('screen')){key=10; route={x1:offense[0].x,y1:offense[0].y,x2:offense[10].x,y2:offense[10].y-2,c1x:b+5*attack,c1y:68};}
 if(p.type.includes('left')){key=9; route={x1:offense[0].x,y1:offense[0].y,x2:offense[9].x,y2:offense[9].y,c1x:b+6*attack,c1y:40};}
 if(p.type.includes('middle')){key=7; route={x1:offense[0].x,y1:offense[0].y,x2:offense[7].x+4*attack,y2:offense[7].y-10,c1x:b+4*attack,c1y:54};}
 if(p.type.includes('run')){key=7; route={x1:offense[7].x,y1:offense[7].y,x2:offense[7].x+8*attack,y2:offense[7].y-10,c1x:b+3*attack,c1y:58};}
 offense[key]={...offense[key],key:true,tag:(p.target||p.name).split(' ').slice(-1)[0]||'WR'};
 offense[0].tag=(p.name||'QB').split(' ').slice(-1)[0]||'QB';
 const ghosts=[{x:route.x2-2*attack,y:route.y2+1},{x:route.x2-4*attack,y:route.y2+3}];
 const ball=p.type.includes('run')?{x:route.x2-1.2*attack,y:route.y2-1}:{x:route.x2,y:route.y2-6};
 return {los,fd,offense,defense,route,ghosts,ball,attack,p};}
function avatar(head,name){return head?`<img src="${esc(head)}" alt="${esc(name)}">`:`<span class="init">${init(name)}</span>`}
function pFig(o,cls){return `<div class="tso-ps886a__player ${cls} ${o.key?'key':''} ${o.fade?'fade':''}" style="left:${o.x}%;top:${o.y}%"><span class="helm"></span><span class="head"></span><span class="torso"></span><span class="arm l"></span><span class="arm r"></span><span class="leg l"></span><span class="leg r"></span>${o.tag?`<span class="tag">${esc(o.tag)}</span>`:''}</div>`;}
function goal(side){return `<div class="tso-ps886a__goal tso-ps886a__goal--${side}"><span class="upright left"></span><span class="upright right"></span><span class="crossbar"></span><span class="post"></span></div>`;}
function lab(halftime){if(halftime?.ready)return{t:'Halftime Lab Ready',s:`${halftime.games||halftime.gameCount||1} games loaded`};if(halftime?.warming||halftime?.eligibleGames?.length)return{t:'Halftime Lab Warming Up',s:'2:00 warning automation active'};return{t:'Halftime Lab Monitoring',s:'Auto-arms near the 2:00 mark in Q2'}}
export function renderNflPlaystageV886AHTML(game,opts={}){ensureNflPlaystageV886AStyles(); const awayC=colors(game,'away'), homeC=colors(game,'home'), P=play(game), S=formation(game), W=wp(game), L=lab(opts.halftime); return `
<section class="tso-ps886a" data-tso-v886a-gamecast style="--away-a:${awayC[0]};--away-b:${awayC[1]};--home-a:${homeC[0]};--home-b:${homeC[1]}">
  <div class="tso-ps886a__hero">
    <div class="tso-ps886a__fieldShell">
      <div class="tso-ps886a__topBoards"><div class="tso-ps886a__topBoard">Football Lives Here</div><div class="tso-ps886a__topBoard"><strong>The Sports Outpost</strong></div><div class="tso-ps886a__topBoard">Analyze · Predict · Win</div></div>
      <div class="tso-ps886a__stadium">
        <div class="tso-ps886a__roofGlow"></div><div class="tso-ps886a__crowd"></div><div class="tso-ps886a__sideline"></div>
        <div class="tso-ps886a__lightTower tso-ps886a__lightTower--left"></div><div class="tso-ps886a__lightTower tso-ps886a__lightTower--right"></div>
        ${goal('left')}${goal('right')}
        <div class="tso-ps886a__fieldStage"><div class="tso-ps886a__fieldPlane"><div class="tso-ps886a__fieldShadow"></div><div class="tso-ps886a__field"><div class="tso-ps886a__endzone tso-ps886a__endzone--away"><div class="tso-ps886a__endText">${esc(tName(game,'away'))}</div></div><div class="tso-ps886a__endzone tso-ps886a__endzone--home"><div class="tso-ps886a__endText">${esc(tName(game,'home'))}</div></div><div class="tso-ps886a__playfield">${yardNums()}<div class="tso-ps886a__line los" style="left:${S.los}%"></div><div class="tso-ps886a__line fd" style="left:${S.fd}%"></div><svg class="tso-ps886a__path" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M ${S.route.x1} ${S.route.y1} Q ${S.route.c1x} ${S.route.c1y}, ${S.route.x2} ${S.route.y2}" fill="none" stroke="#63d8ff" stroke-width="0.9" stroke-dasharray="2.2 1.4" stroke-linecap="round"/><path d="M ${S.route.x2-2*S.attack} ${S.route.y2-1} L ${S.route.x2} ${S.route.y2} L ${S.route.x2-1.2*S.attack} ${S.route.y2+2}" fill="none" stroke="#fff" stroke-width="0.7" stroke-linecap="round"/></svg>${S.offense.map(o=>pFig(o,'off')).join('')}${S.defense.map(o=>pFig(o,'def')).join('')}${S.ghosts.map(o=>pFig({...o,fade:true},'off')).join('')}<div class="tso-ps886a__ball" style="left:${S.ball.x}%;top:${S.ball.y}%"></div></div><div class="tso-ps886a__tso50">TSO</div></div></div></div>
        <div class="tso-ps886a__legend"><span><i></i>Line of Scrimmage</span><span><i class="fd"></i>First Down</span><span><i class="path"></i>Play Path</span></div>
      </div>
    </div>
  </div>
  <div class="tso-ps886a__panels">
    <article class="tso-ps886a__panel"><div class="tso-ps886a__title">Current Play <span class="tso-ps886a__chip">Live</span></div><div class="tso-ps886a__row"><div class="tso-ps886a__avatar">${avatar(P.head,P.name)}</div><div><div class="tso-ps886a__pname">${esc(dd(game))} &nbsp;|&nbsp; ${esc(fp(game))}</div><div class="tso-ps886a__psub">${esc(P.name)} · ${esc(P.pos)} #${esc(P.no)}</div></div></div><div class="tso-ps886a__copy">${esc(P.desc)}</div><div class="tso-ps886a__stats"><div><b>${esc(P.plays)}</b><small>Plays</small></div><div><b>${esc(P.yards)}</b><small>Yards</small></div><div><b>${esc(P.time)}</b><small>Time</small></div><div><b>${esc(P.yds)}</b><small>Yds Play</small></div></div></article>
    <article class="tso-ps886a__panel"><div class="tso-ps886a__title">Featured Player ${tLogo(game,possessionSide(game))?`<img src="${esc(tLogo(game,possessionSide(game)))}" alt="" style="height:20px;object-fit:contain">`:''}</div><div class="tso-ps886a__row"><div class="tso-ps886a__avatar">${avatar(P.head,P.name)}</div><div><div class="tso-ps886a__pname">${esc(P.name)}</div><div class="tso-ps886a__psub">${esc(P.pos)} #${esc(P.no)}</div></div></div><div class="tso-ps886a__stats"><div><b>${esc(P.stats.compAtt||'8/10')}</b><small>Comp/Att</small></div><div><b>${esc(P.stats.yards||'96')}</b><small>Yds</small></div><div><b>${esc(P.stats.td||'0')}</b><small>TD</small></div><div><b>${esc(P.stats.rtg||P.stats.qbr||'118.3')}</b><small>RTG</small></div></div></article>
    <article class="tso-ps886a__panel"><div class="tso-ps886a__title">Win Probability</div><div class="tso-ps886a__wp"><span>${esc(tName(game,'away'))} ${W.away}%</span><span>${W.home}% ${esc(tName(game,'home'))}</span></div><div class="tso-ps886a__chart"><svg viewBox="0 0 100 80" preserveAspectRatio="none"><path d="${chartPath(P.chart)}" fill="none" stroke="#22afff" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/><circle cx="96" cy="${80-clamp((P.chart||[]).slice(-1)[0]||50,0,100)*.62}" r="3.4" fill="#61c9ff"/></svg></div><div class="tso-ps886a__axis"><span>1st</span><span>2nd</span><span>3rd</span><span>4th</span></div></article>
    <article class="tso-ps886a__panel"><div class="tso-ps886a__title">Drive Summary <span style="color:#b9ddff;text-transform:none;letter-spacing:0">View All ›</span></div><div class="tso-ps886a__summary">${P.drive.map(r=>`<div class="tso-ps886a__srow ${r.current?'cur':''}"><i></i><span>${esc(r.text)}</span><small>${esc(r.dd||'')}</small><small>${esc(r.fp||'')}</small></div>`).join('')}</div></article>
  </div>
  <div class="tso-ps886a__footer"><div class="tso-ps886a__brand"><span>The Sports Outpost</span><strong>Different Looks. A Higher Standard.</strong></div><div class="tso-ps886a__nav"><span><i>◔</i>Analyze</span><span><i>◎</i>Predict</span><span><i>▷</i>Watch</span><span><i>🏆</i>Win</span></div><div class="tso-ps886a__lab"><i>🧪</i><div>${L.t}<small>${L.s}</small></div></div></div>
</section>`;}
function placePossessionFootball(root,game){if(!root||typeof document==='undefined')return; root.querySelectorAll('.tso-possession-football').forEach(n=>n.remove()); const poss=possessionSide(game); const names=poss==='away'?[tName(game,'away'),tAb(game,'away')]:[tName(game,'home'),tAb(game,'home')]; const candidates=[...root.querySelectorAll('h1,h2,h3,h4,div,span,strong,p')].filter(el=>{const txt=(el.textContent||'').trim(); return txt && names.some(n=>txt===n||txt.endsWith(n)||txt.includes(n));}).sort((a,b)=>a.textContent.length-b.textContent.length); const target=candidates[0]; if(!target)return; const icon=document.createElement('span'); icon.className='tso-possession-football'; icon.textContent='🏈'; icon.style.verticalAlign='middle'; if(poss==='home') target.prepend(icon); else target.append(icon);}
export function mountOrUpdateNflPlaystageV886A(root,game,opts={}){if(typeof document==='undefined'||!root||!game)return; ensureNflPlaystageV886AStyles(); placePossessionFootball(root,game); const host=root.querySelector('[data-tso-v886a-anchor]')||(()=>{const el=document.createElement('div'); el.dataset.tsoV886aAnchor='1'; const main=root.querySelector('[data-tso-gamecast-main],.tso-gamecast-main,.nfl-gamecast-main,.nfl-gamecast,.gamecast-view,main')||root; const score=main.querySelector('[data-score-header],.scoreboard,.tso-scoreboard,.nfl-scoreboard,header'); if(score&&score.nextSibling)score.parentNode.insertBefore(el,score.nextSibling); else main.prepend(el); return el;})(); host.innerHTML=renderNflPlaystageV886AHTML(game,opts); setTimeout(()=>placePossessionFootball(root,game),80); setTimeout(()=>placePossessionFootball(root,game),350);}
