import {applyLineups,rosterURL,lineupLabel,lineupState,lineupReady} from './lineups.js?v=90.2';
import {quoteFor} from './odds.js?v=90.1';
import {API,getJSON,loadScoreboard,mergeSummary,freshGame,threats,text as esc,imageUrl} from './data.js?v=90.2';
let research=null,odds=null,sim=null;
let doc=null,tab='slate',gameId=null,market='sog',busy=false,error=false,timer=null;
const tabs={slate:'Slate',live:'Live',feed:'Goal Feed',props:'Props'};
const markets={atg:'Anytime Goal',sog:'Shots on Goal',points:'Points',assists:'Assists',blocks:'Blocked Shots',saves:'Goalie Saves'};
const empty=s=>`<p class="hk-empty">${esc(s)}</p>`;
const photo=p=>imageUrl(p.photo)?`<img src="${esc(p.photo)}" alt="${esc(p.name)}" loading="lazy">`:'<span class="hk-avatar">🏒</span>';
const score=g=>`${esc(g.away.abbr)} ${g.away.score??'—'} · ${esc(g.home.abbr)} ${g.home.score??'—'}`;
const time=g=>g.status==='pre'?new Date(g.startTime).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):g.detail;
export function selectTab(next){if(!tabs[next])return;tab=next;window.DW_nhlTab=tab;render();window.renderSidebarSports?.();}
function gameCards(games){return games.map(g=>`<button class="hk-card hk-game" data-hk-game="${esc(g.id)}"><small>${g.seasonType===1?'Preseason · ':''}${esc(time(g))}</small><b>${esc(g.away.name)} @ ${esc(g.home.name)}</b>${g.status!=='pre'?`<strong>${score(g)}</strong>`:''}<span>${esc(g.venue)}</span><small>${esc(lineupLabel(g))}</small><small>${g.status==='in'&&!freshGame(g)?'Waiting for fresh game data':'Open game →'}</small></button>`).join('');}
function goals(){const rows=(doc?.games||[]).flatMap(g=>(g.goals||[]).map(p=>({g,p}))).sort((a,b)=>Date.parse(b.g.startTime)-Date.parse(a.g.startTime)||b.p.period-a.p.period||Date.parse(b.p.timestamp)-Date.parse(a.p.timestamp));return rows.map(({g,p})=>`<article class="hk-card hk-goal">${photo(p.scorer)}<div><small>${esc(p.team)} · P${p.period} ${esc(p.clock)} · ${esc(p.strength)}</small><h3>${esc(p.scorer.name)}</h3><p>${esc(p.text)}</p><small>${score({...g,away:{...g.away,score:p.awayScore},home:{...g.home,score:p.homeScore}})}</small></div></article>`).join('')||empty('No goals reported for this slate yet. Scorers and assists appear here during games.');}
function forecast(p){const game=sim?.games?.find(g=>g.gameId===p.game.id);if(!game?.ready||!Number.isFinite(Date.parse(game.generatedAt))||Date.now()-Date.parse(game.generatedAt)>120000||Date.parse(game.generatedAt)>Date.now()+60000)return '';
 const g=p.game;if(game.state!==lineupState(g)||!lineupReady(g))return '';
 const model=game.players?.find(x=>x.id===p.id)?.metrics?.[market==='atg'?'goals':market];return model?`${market==='atg'?'Goal chance '+(model.atLeastOne*100).toFixed(1)+'% · ':''}Mean ${model.mean.toFixed(2)} · Median ${model.median} · ${game.iterations.toLocaleString()} sims`:'';}
function baseline(p){const history=research?.players?.[p.id];const key=market==='atg'?'goals':market;const rate=history?.rates?.[key];return rate==null?'Season baseline pending':`${history.season-1}–${String(history.season).slice(-2)} avg ${rate.toFixed(2)}/game (${history.games} GP)`;}
function priceText(p){if(p.game.status!=='pre')return p.game.status==='post'?'Market closed':'Live odds pending';const q=quoteFor(odds,p.game.id,p.id,market);if(!q)return 'Odds pending';const price=v=>v==null?'—':v>0?'+'+v:String(v);return `${q.book} · ${market==='atg'?'Goal':q.line} · ${market==='atg'?'Yes':'O'} ${price(q.over)} / ${market==='atg'?'No':'U'} ${price(q.under)}`;}
function props(){const ps=(doc?.games||[]).flatMap(g=>g.players.map(p=>({...p,game:g}))).filter(p=>market==='saves'?p.position==='G':p.position!=='G');return `<label class="hk-filter">Player market <select id="hk-market">${Object.entries(markets).map(([k,v])=>`<option value="${k}" ${k===market?'selected':''}>${v}</option>`).join('')}</select></label><p class="hk-note">Last-season averages provide a baseline. Game projections require confirmed lineups and goalie status. Sportsbook quotes appear when available.</p>${ps.map(p=>`<article class="hk-card hk-player">${photo(p)}<div><b>${esc(p.name)}</b><small>${esc(p.team)} · ${esc(p.position)} · ${esc(p.game.away.abbr)} @ ${esc(p.game.home.abbr)}</small><small>${esc(p.availability)}</small></div><div><b>${p.current?.[market==='atg'?'goals':market]??'—'}</b><small>Current ${market==='atg'?'goals':esc(markets[market].toLowerCase())}</small><small>${esc(baseline(p))}</small><small>${esc(forecast(p))}</small><small>${esc(priceText(p))}</small></div></article>`).join('')||empty('Player rosters are not available yet.')}`;}
function live(){const games=doc?.games||[];const g=games.find(g=>g.id===gameId)||games.find(g=>g.status==='in')||games[0];if(!g)return empty('No NHL games are scheduled for this slate.');return `<label class="hk-filter">Game <select id="hk-game">${games.map(x=>`<option value="${esc(x.id)}" ${x.id===g.id?'selected':''}>${esc(x.away.abbr)} @ ${esc(x.home.abbr)}</option>`).join('')}</select></label>${gameCards([g])}${g.status==='pre'?empty('Gamecast opens at puck drop. Roster and goalie confirmation appears above as it becomes available.'):`<h3>Recent plays</h3>${g.summaryUnavailable?empty('Play-by-play is temporarily unavailable.'):g.plays.map(p=>`<div class="hk-play"><small>P${p.period} · ${esc(p.clock)}</small><p>${esc(p.text)}</p></div>`).join('')||empty('Waiting for the first reported play.')}<h3>Box score</h3><div class="hk-table"><table><thead><tr><th>Player</th><th>G</th><th>A</th><th>SOG</th><th>BLK</th><th>SV</th><th>TOI</th></tr></thead><tbody>${g.players.map(p=>`<tr><th>${esc(p.name)} <small>${esc(p.team)}</small></th>${['goals','assists','sog','blocks','saves','toi'].map(k=>`<td>${esc(p.current?.[k]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}`;}
export function commandCenterHTML(){const games=doc?.games||[],liveGames=games.filter(g=>freshGame(g)),alerts=threats(doc);return `<div class="cc-col-title">Hockey</div><div class="cc-kpi-row"><div class="cc-kpi-tile"><b>${liveGames.length}</b><span>Live Now</span></div><div class="cc-kpi-tile"><b>${games.some(g=>g.summaryUnavailable)?'—':games.reduce((n,g)=>n+(g.goals?.length||0),0)}</b><span>Goals</span></div><div class="cc-kpi-tile"><b>${alerts.length}</b><span>Threat Alerts</span></div></div>${alerts.map(a=>`<button class="cc-alert-row hk-alert" data-hk-game="${esc(a.gameId)}"><span class="cc-alert-text">${esc(a.title)}<small>${esc(a.detail)}</small></span><span>WATCH →</span></button>`).join('')||empty(error?'Waiting for fresh hockey data.':liveGames.length?'No active threats right now.':'No live NHL games right now. Power-play, shot and hat-trick watches appear during games.')}`;}
function render(){const host=document.getElementById('nhlView');if(host){host.innerHTML=`<header class="hk-header"><small>🏒 NHL${doc?.season?' · '+esc(doc.season):''}</small><h1>${tabs[tab]}</h1><p>${doc?.date?esc(doc.date)+' slate · ':''}${error?'Waiting for fresh hockey data':doc?'Updated '+new Date(doc.generatedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Loading hockey…'}</p></header><section>${!doc?empty('Connecting to the NHL feed…'):tab==='slate'?`<div class="hk-grid">${gameCards(doc.games)}</div>${doc.games.length?'':empty('No games are scheduled for this slate.')}`:tab==='feed'?goals():tab==='props'?props():live()}</section><footer class="hk-note">NHL game data: ESPN. Shootout attempts are excluded from the Goal Feed and player goal totals.</footer>`;}
 const cc=document.getElementById('ccHockeyCol');if(cc?.classList.contains('active'))cc.innerHTML=commandCenterHTML();window.refreshCommandCenterAlertState?.();}
export async function refresh(){if(busy||document.hidden)return;busy=true;try{
 const [next,r,o,s]=await Promise.all([loadScoreboard(),getJSON('./slates/nhl-research.json').catch(()=>null),getJSON('./slates/nhl-odds.json').catch(()=>null),getJSON('./slates/nhl-sim.json').catch(()=>null)]);if(r)research=r;if(o)odds=o;if(s)sim=s;
 for(const g of next.games){const prior=doc?.games?.find(x=>x.id===g.id);g.players=prior?.players||[];
  if(['in','post'].includes(g.status)){try{Object.assign(g,mergeSummary(g,await getJSON(`${API}/summary?event=${g.id}`)));}catch{g.summaryUnavailable=true;}}
  const evidence={};
  if(g.status!=='pre'||Date.parse(g.startTime)-Date.now()<10800000)await Promise.all([g.away,g.home].map(async t=>{try{evidence[t.id]=await getJSON(rosterURL(g,t));}catch{}}));
  Object.assign(g,applyLineups(g,evidence));
 }
 doc=next;error=false;
 }catch{error=true;}finally{busy=false;render();}}
export async function mount(){if(!doc){try{doc=await getJSON('./slates/nhl.json');}catch{error=true;}}selectTab(window.DW_nhlPendingTab||tab);window.DW_nhlPendingTab=null;render();if(!timer){refresh();timer=setInterval(()=>{if(location.hash==='#nhl'||document.getElementById('ccHockeyCol')?.classList.contains('active'))refresh();},30000);}}
window.DW_NHL_COMMAND_CENTER={html:commandCenterHTML,alerts:()=>threats(doc),refresh:()=>mount()};
window.DW_openNhlTab=next=>{window.DW_nhlPendingTab=next;if(location.hash!=='#nhl')location.hash='nhl';else selectTab(next);};
document.addEventListener('click',e=>{const b=e.target.closest('[data-hk-tab],[data-hk-game]');if(!b)return;if(b.dataset.hkGame){gameId=b.dataset.hkGame;window.closeCommandCenter?.();window.DW_openNhlTab('live');}else selectTab(b.dataset.hkTab);});
document.addEventListener('change',e=>{if(e.target.id==='hk-market'){market=e.target.value;render();}if(e.target.id==='hk-game'){gameId=e.target.value;render();}});
