create table if not exists public.nfl_watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  player_id text not null,
  player_name text not null,
  team text,
  created_at timestamptz not null default now(),
  unique (user_id, player_id)
);

alter table public.nfl_watchlist enable row level security;
grant select, insert, delete on table public.nfl_watchlist to authenticated;

create policy "users read their own nfl watchlist"
on public.nfl_watchlist for select to authenticated
using ((select auth.uid()) = user_id);

create policy "users add to their own nfl watchlist"
on public.nfl_watchlist for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "users remove from their own nfl watchlist"
on public.nfl_watchlist for delete to authenticated
using ((select auth.uid()) = user_id);
